# Generated by Django 3.0.6 on 2020-08-13 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_place_information_end_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='available_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='photos')),
                ('item_name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('installed_vendor', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='place_information',
        ),
        migrations.AddField(
            model_name='available_data',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.categories'),
        ),
    ]
