# Generated by Django 3.0.6 on 2020-08-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20200813_0032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='available_data',
        ),
    ]
