# Generated by Django 3.0.6 on 2020-08-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_available_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='available_item',
        ),
        migrations.DeleteModel(
            name='categories',
        ),
    ]
