# Generated by Django 3.0.6 on 2020-08-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20200815_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_item',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
    ]
